---
- name: Configure Fedora workstation apps
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars_files:
    - vars_dnf.yml
    - vars_flatpak.yml

  tasks:
    - name: Ensure DNF packages are installed
    # Note: package module uses dnf on Fedora
      ansible.builtin.package:
        name: "{{ dnf_packages }}"
        state: present

    - name: Ensure Flatpak is installed (if any Flatpaks are listed)
      ansible.builtin.package:
        name: flatpak
        state: present
      when: (flatpak_user_apps | length > 0) or (flatpak_system_apps | length > 0)

    - name: Ensure Flathub remote exists (common default)
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
      when: (flatpak_user_apps | length > 0) or (flatpak_system_apps | length > 0)

    - name: Install user Flatpak apps
      become: false
      community.general.flatpak:
        name: "{{ flatpak_user_apps }}"
        state: present
        method: user
        remote: flathub
      when: flatpak_user_apps is defined and (flatpak_user_apps | length > 0) and (flatpak_user_apps[0] != [])

    - name: Install system Flatpak apps
      community.general.flatpak:
        name: "{{ flatpak_system_apps }}"
        state: present
        method: system
        remote: flathub
      when: flatpak_system_apps is defined and (flatpak_system_apps | length > 0) and (flatpak_system_apps[0] != [])
